#!/bin/sh
# Handler format: .
#
# The script file .sh  must be located at the root of your
# function's deployment package, alongside this bootstrap executable.
source $(dirname "$0")/"$(echo "$_HANDLER" | cut -d. -f1).sh"

RUNTIME_API_ADDRESS="http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation"

while true
do
    # Request the next event from the Lambda runtime
    HEADERS="$(mktemp)"
    EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "$RUNTIME_API_ADDRESS/next")
    INVOCATION_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

    # Execute the handler function from the script
    echo "$EVENT_DATA"
    RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) "$EVENT_DATA")

    if [ "$?" = "0" ]; then
      # Send the response to Lambda runtime with success
      curl -sS -X POST "$RUNTIME_API_ADDRESS/$INVOCATION_ID/response" -d "$RESPONSE"
    else
      # Send the response to Lambda runtime with error
      curl -sS -X POST "$RUNTIME_API_ADDRESS/$INVOCATION_ID/error" -d "$RESPONSE"
    fi

done